### PR TITLE
Pr 16bit addressing support

### PR DESCRIPTION
**Pull request by viorz**
TMS320 have 16-bits addressing, so
1.   (uint8_t) same (uint16_t)
2.   sizeof(float) is 2
3.   union not same like STM32, because type uint8_t does not exist in hardware

Example:
     union
     {
         uint64_t u8;
         uint64_t u16;
         uint64_t u32;
         uint64_t u64;
         uint8_t bytes[8];
     } storage;

     address:|   bytes:        |   u64:                      |   u32:                       |   u16:    |   u8:
     0x00      |   bytes[0]    |   (u64         )&0xFF  |   (u32         )&0xFF  |   u16     |   u8
     0x01      |   bytes[1]    |   (u64>>16)&0xFF  |   (u32>>16)&0xFF  |
     0x02      |   bytes[2]    |   (u64>>32)&0xFF  |
     0x03      |   bytes[3]    |   (u64>>48)&0xFF  |
     0x04      |   bytes[4]    |
     0x05      |   bytes[5]    |
     0x06      |   bytes[6]    |
     0x07      |   bytes[7]    |

### CODE REVIEW

**Comment by tridge** [comment]
@viorz thanks for the contribution!
what testing have you done on this?

**Comment by tridge** [comment]
I've pushed some fixes to try to get CI to pass

**Comment by tridge** [comment]
@viorz it now builds and passes tests, but please let me know what testing you have done so I can be sure it really works

**Comment by tridge** [comment]
@viorz any update?

**Comment by EMBRMP2** [comment]
@viorz have you tested this commit with any TMS320 microcontroller

**Comment by tridge** [comment]
I believe this will work, and will merge, hopefully someone with this type of MCU will test

**Comment by viorz** [comment]
I tested it on TMS320F280049 and it work.

**Pull request merged**
